spring.application.name=NectUs

spring.datasource.url=jdbc:postgresql://localhost:5433/nectus
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiry=900000
app.jwt.refresh-token-expiry=2592000000
logging.level.org.springframework.security=DEBUG