spring.application.name=NectUs

spring.datasource.url=jdbc:postgresql://localhost:5433/nectus
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# AWS S3
aws.s3.bucket-name=${AWS_BUCKET_NAME}
aws.s3.region=${AWS_REGION}
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiry=900000
app.jwt.refresh-token-expiry=2592000000
logging.level.org.springframework.security=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
spring.mvc.throw-exception-if-no-handler-found=true
logging.level.org.springframework.web=DEBUG